'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class imgResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TifyVBNET.imgResource", GetType(imgResource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _16_colours() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_16_colours", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _16_colours__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_16_colours__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _20_colours() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_20_colours", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _20_colours__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_20_colours__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _32_colours() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_colours", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _32_colours__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32_colours__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _5_Ramps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_Ramps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _5_Ramps__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5_Ramps__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property amber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("amber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property amber__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("amber__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property blue_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property blue_orange__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue_orange__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property brain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property brain__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brain__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property brown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property brown__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brown__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cmy_cyan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmy_cyan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cmy_cyan__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmy_cyan__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cmy_magneta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmy_magneta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cmy_magneta__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmy_magneta__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cmy_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmy_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cmy_yellow__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmy_yellow__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cold__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cold__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cool__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cool__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property edges() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edges", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property edges__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edges__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Fire__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property gem_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gem_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property gem_256__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gem_256__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property gold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property gold__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gold__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property GreenFire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenFire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property GreenFire__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenFire__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Grey__Reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grey__Reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property HiLo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HiLo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property HiLo__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HiLo__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property HotGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HotGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property HotGreen__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HotGreen__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property HotRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HotRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property HotRed__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HotRed__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property hue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property hue__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hue__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Ice__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ice__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property invert_gray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invert_gray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property invert_gray__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invert_gray__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property log_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property log_down__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log_down__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property log_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property log_up__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log_up__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neon_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neon_blue__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon_blue__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neon_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neon_green__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon_green__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neon_magenta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon_magenta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neon_magenta__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon_magenta__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neon_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property neon_red__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("neon_red__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Phase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Phase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Phase__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Phase__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Random() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Random__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Random__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property red_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property red_blue__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_blue__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property RedHot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedHot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property RedHot__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedHot__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property rgb_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rgb_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property rgb_blue__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rgb_blue__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property rgb_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rgb_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property rgb_green__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rgb_green__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property rgb_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rgb_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property rgb_red__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rgb_red__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Spectrum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spectrum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Spectrum__reverse_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spectrum__reverse_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
